export const DATA_IS_LOADING = 'DATA_IS_LOADING';
export const ALERT = 'ALERT';

/* Customers */
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
export const UPDATE_CUSTOMER_LIST = 'UPDATE_CUSTOMER_LIST';
export const OPEN_CUSTOMER_MODAL = 'OPEN_CUSTOMER_MODAL';
export const CLOSE_CUSTOMER_MODAL = 'CLOSE_CUSTOMER_MODAL';

/* Products */
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST';
export const OPEN_PRODUCT_MODAL = 'OPEN_PRODUCT_MODAL';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';

/* Invoices */
export const GET_INVOICE_PRODUCT_META = 'GET_INVOICE_PRODUCT_META';
export const GET_INVOICE_CUSTOMER_META = 'GET_INVOICE_CUSTOMER_META';
export const GET_INVOICE_LIST = 'GET_INVOICE_LIST';
export const UPDATE_INVOICE_LIST = 'UPDATE_INVOICE_LIST';
export const GET_INVOICE = 'GET_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const GET_INVOICE_ITEMS = 'GET_INVOICE_ITEMS';
export const OPEN_INVOICE_MODAL = 'OPEN_INVOICE_MODAL';
export const CLOSE_INVOICE_MODAL = 'CLOSE_INVOICE_MODAL';
